title: "Cyndi Cavanaugh"
author: "Charles \"Cyndi\" Cavanaugh, Ph.D."
description: "Copyright &copy; 2023 Charles \"Cyndi\" Cavanaugh, Ph.D. (she/her)"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Home, icon: home}
  - {url: "https://youtube.com/@cyndi5hunt", title: Subscribe}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/cyndi5"}
  - {title: Subscribe, icon: youtube, url: "https://youtube.com/@cyndi5hunt"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
